packages:
  - "apps/*"
  - "packages/*"
catalogs:
  backend:
    "@nestjs/platform-express": ^11.0.1
  build:
    "@vitejs/plugin-react": ^4.3.4
    tsup: ^8.5.0
    vite: ^6.0.1
  cli:
    pncat: ^0.2.3
  dev:
    "@nestjs/cli": ^11.0.0
    "@nestjs/schematics": ^11.0.0
    "@nestjs/testing": ^11.0.1
    "@swc/cli": ^0.6.0
    "@swc/core": ^1.11.22
    globals: ^16.0.0
    source-map-support: ^0.5.21
    supertest: ^7.0.0
    ts-loader: ^9.5.2
    ts-node: ^10.9.2
    tsconfig-paths: ^4.2.0
    typescript: ^5.7.3
  lint:
    "@eslint/eslintrc": ^3.2.0
    "@eslint/js": ^9.18.0
    eslint: ^9.18.0
    eslint-config-prettier: ^10.0.1
    eslint-plugin-only-warn: ^1.1.0
    eslint-plugin-prettier: ^5.2.2
    eslint-plugin-react: ^7.37.4
    eslint-plugin-react-hooks: ^5.0.0
    eslint-plugin-react-refresh: ^0.4.14
    lint-staged: ^15.5.1
    prettier: ^3.4.2
    typescript-eslint: ^8.20.0
  monorepo:
    turbo: ^2.5.2
  network:
    "@nestjs/axios": ^4.0.0
    axios: ^1.9.0
  node:
    cross-env: ^7.0.3
  prod:
    "@nestjs-modules/ioredis": ^2.0.2
    "@nestjs/common": ^11.0.1
    "@nestjs/config": ^4.0.2
    "@nestjs/core": ^11.0.1
    "@nestjs/jwt": ^11.0.0
    "@nestjs/passport": ^11.0.5
    "@nestjs/schedule": ^6.0.0
    "@nestjs/swagger": ^11.1.5
    "@prisma/client": ^6.6.0
    cos-nodejs-sdk-v5: ^2.14.7
    date-fns: ^4.1.0
    ioredis: ^5.6.1
    nodemailer: ^6.10.1
    openai: ^4.98.0
    passport: ^0.7.0
    passport-jwt: ^4.0.1
    pixi.js: ^8.4.1
    prisma: ^6.6.0
    react: ^18.3.1
    react-dom: ^18.3.1
    reflect-metadata: ^0.2.2
    rxjs: ^7.8.1
    uuid: ^11.1.0
    zustand: ^5.0.1
  test:
    jest: ^29.7.0
    ts-jest: ^29.2.5
  types:
    "@types/express": ^5.0.0
    "@types/jest": ^29.5.14
    "@types/multer": ^1.4.12
    "@types/node": ^22.10.7
    "@types/nodemailer": ^6.4.17
    "@types/react": ^18.3.12
    "@types/react-dom": ^18.3.1
    "@types/supertest": ^6.0.2
    "@types/uuid": ^10.0.0
  utils:
    zod: ^3.23.8
